#!/usr/bin/env python3
#
# Copyright (C) 2017, Jaguar Land Rover
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
#  * Gustavo Noronha <gustavo.noronha@collabora.com>
#  * Shane Fagan <shane.fagan@collabora.com>

import sys
import os
import argparse
import yaml
import ast
import threading
import time
from ipc.loader import load_plugin, LoaderError
import os

LOGIC_REPLACE = {'||': 'or',
                 '&&': 'and',
                 'true': 'True',
                 'false': 'False'}

KEYWORDS = ['condition', 'emit']

LOG_FILE_PATH_DEFAULT = 'vsm.log'

start_time_ms = 0
logger = None

class Logger(object):
    '''
        Utility class for logging messages
    '''

    def __init__(self, pipeout_fd):
        self.pipeout_fd = pipeout_fd

    def i(self, msg, timestamp=True):
        '''
            Log an informative (non-error) message
        '''
        os.write(self.pipeout_fd, (msg + '\n').encode('UTF-8'))

    def e(self, msg, timestamp=True):
        '''
            Log an error
        '''
        os.write(self.pipeout_fd, (msg + '\n').encode('UTF-8'))

    def signal(self, signal, value):
        '''
            Log a signal emission
        '''
        # NOTE: the "[SIGNUM]" field is a temporary placeholder for the signal
        # ID
        msg_final = '{},{},[SIGNUM],{}'.format(get_runtime(), signal,
                repr(value))

        print(msg_final)

class State(object):
    '''
        Class to handle states
    '''
    def __init__(self, initial_state, rules):
        class VariablesStorage(object):
            pass
        self.variables = VariablesStorage()

        self.rules = {}
        with open(rules) as rules_file:
            self.parse_rules(rules_file)

        if initial_state:
            with open(initial_state) as f:
                data = yaml.load(f.read())

                for item in data:
                    item = item.replace(" ", "").split("=")
                    vars(self.variables)[item[0]] = item[1]

    def handle_emit(self, data, condition):
        signal = data["emit"]["signal"]
        value = data["emit"]["value"]

        if "delay" in data["emit"].keys():
            action = "threading.Thread(target=delayed_emit, args=( \
                            \'{}\', \'{}\', {})).start()".format(signal,
                            value, data["emit"]["delay"])
        else:
            action = "emit(\'{}\', \'{}\')".format(signal, value)

        action = ast.parse(action)

        if condition == True:
            return action.body[0]
        else:
            rule = compile(action, '<string>', 'exec')
            exec(rule)

    def handle_condition(self, data):
        condition = data["condition"]
        condition_expr = ast.parse(condition).body[0]

        action_true_1_body = self.handle_emit(data, True)

        action_true_2_code = self.generate_condition_code(condition, True)
        action_true_2 = ast.parse(action_true_2_code)

        action_false_code = self.generate_condition_code(condition, False)
        action_false = ast.parse(action_false_code)

        ifnode = ast.If(condition_expr.value,
                [action_true_1_body, action_true_2.body[0]],
                [action_false.body[0]])
        ast_module = ast.Module([ifnode])

        ast.fix_missing_locations(ast_module)

        rule = compile(ast_module, '<string>', 'exec')
        self.add_rule(condition_expr, rule)

    def generate_condition_code(self, condition, result):
        return "logger.i(\"condition: ({}) => {}\")".format(condition,
                str(result))

    def __parse_items(self, item):
        keys = list(item.keys())
        if "condition" in item:
            self.handle_condition(item)
        elif "emit" in item:
            self.handle_emit(item, False)

    def parse_rules(self, rules_file):
        '''
            Parse YAML rules for policy manager and return ast code.
        '''
        data = rules_file.read()

        # Translate logical operations to Python, so that they
        # can be compiled.
        for key, value in LOGIC_REPLACE.items():
             data = data.replace(key, value).strip()

        data = yaml.safe_load(data)
        # Currently we support only lists in yaml at base level
        if issubclass(type(data), list):
            for item in data:
                self.__parse_items(item)

    def add_rule(self, condition, rule):
        tracked_signal = None

        names = []
        attributes = []
        for node in ast.walk(condition):
            if isinstance(node, ast.Attribute):
                attributes.append(node.attr)
            if isinstance(node, ast.Name):
                name = node.id
                if attributes:
                    name = '.'.join(reversed(attributes + [name]))
                    attributes = []
                names.append(name)

        for signal_name in names:
            if not signal_name in self.rules:
                self.rules[signal_name] = []
            self.rules[signal_name].append(rule)

    def got_signal(self, signal, value):
        vars(self.variables)[signal] = value

        logger.i("State = {")
        for k, v in sorted(vars(self.variables).items()):
            logger.i("{} = {}".format(k, v))
        logger.i("}")

        # No conditions based on the signal that was emitted,
        # nothing to be done.
        if not signal in self.rules:
            return

        for rule in self.rules[signal]:
            try:
                exec(rule, globals(), vars(self.variables))
            except NameError:
                # Names used in rules are not always present
                # in the state.
                pass


def send(signal, value):
    logger.signal(signal, value)

def delayed_emit(signal, value, delay):
    time.sleep(delay/1000)
    emit(signal, value)

def emit(signal, value):
    send(signal, value)

def process(state, signal, value):
    '''
        Handle the emitting of signals and adding values to state
    '''
    def is_string(value):
        return (value[0] == '"' or value[0] == "'") and \
            (value[-1] == '"' or value[-1] == "'")

    def is_bool(value):
        return value == 'true' or value == 'false'

    # from str to int or float (if that is needed)
    if is_string(value):
        value = value[1:-1]
    elif is_bool(value):
        value = value == 'true' or False
    else:
        if value.isalnum():
            if '.' in value:
                value = float(value)
            else:
                value = int(value)

    state.got_signal(signal, value)

def log_processor(pipein_fd, log_file_path):
    pipein = os.fdopen(pipein_fd)
    log_file = sys.stdout

    if log_file_path == None or log_file_path == '':
        log_file_path = LOG_FILE_PATH_DEFAULT

    if log_file_path != '-':
        try:
            log_file = open(log_file_path, 'w')
        except Exception as e:
            log_file.write("failed to open log file '{}': {}\n".format(
                log_file_path, e))

    for line in pipein:
        log_file.write(line)
        log_file.flush()

    if log_file_path:
        log_file.close()

    pipein.close()

def receive():
    '''
        Loop to grab logic from stdin
    '''
    for line in sys.stdin:
        line = line.replace(" ", "").strip('\n')
        if line == "":
            # Ignore blank lines
            pass
        if line == "quit":
            exit(0)
        elif "=" in line:
            line = line.split("=")
            return (line[0], line[1])
        else:
            return (line, None)

def run(state):
    try:
        while True:
            message = receive()
            if message == None:
                exit(0)

            signal, value = message
            # 'quit' signal to close VSM endpoint.
            if signal == 'quit':
                send('', '')
                break

            process(state, signal, value)
    except KeyboardInterrupt:
        exit(0)

def get_runtime():
    return round(time.perf_counter() * 1000 - start_time_ms)

if __name__ == "__main__":
    start_time_ms = round(time.perf_counter() * 1000)

    parser = argparse.ArgumentParser()
    parser.add_argument('--initial-state', type=str,
                        help='Initial state, yaml file', required=False)
    parser.add_argument('rules', type=str,
                        help='yaml rules configuration')
    parser.add_argument('--ipc-module', type=str, help='Load IPC module')
    parser.add_argument('--log-file', type=str,
            help='Write extra (non-signal emission) output to this file')
    args = parser.parse_args()

    # fork separate process to handle logging so we don't block main process
    pipein_fd, pipeout_fd = os.pipe()
    if os.fork() == 0:
        os.close(pipeout_fd)
        log_processor(pipein_fd, args.log_file)
    else:
        os.close(pipein_fd)

        logger = Logger(pipeout_fd)
        if args.ipc_module:
            # Load IPC plugin.
            # Override the receive/send functions with the plugin version.
            try:
                load_plugin('ipc.{}'.format(args.ipc_module))
            except LoaderError as err:
                logger.e(err)
                exit(1)

        state = State(args.initial_state, args.rules)
        run(state)
